version: '3.8'

services:
  # MariaDB Service - Task 1
  kafeshka-mariadb:
    container_name: kafeshka-db
    image: mariadb:10.3.7
    environment:
      - MYSQL_USER=kafeshka
      - MYSQL_ROOT_PASSWORD=test123
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=kafeshka
      - SPRING_MYSQL_JDBC_URL=jdbc:mysql://172.10.18.2:3376/kafeshka?useUnicode=true&characterEncoding=utf8&useSSL=false
    volumes:
      - "./volumes/kafeshka/mysql_init.sql:/docker-entrypoint-initdb.d/mysql_init.sql"
    ports:
      - '3376:3306' # Expose MariaDB port as 3376 externally, keep 3306 internally
    networks:
      kafeshanet:
        ipv4_address: 172.10.18.2 # Custom IPv4 address for MariaDB

  # Spring Boot Application - Task 2
  spring-app:
    image: redcopy/kafeshka-rs:latest
    container_name: kafeshka-rs
    depends_on:
      - kafeshka-mariadb # Ensure the Spring Boot app starts after MariaDB
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://172.10.18.2:3376/kafeshka?useUnicode=true&characterEncoding=utf8&useSSL=false # Use the custom IPv4 address
      SPRING_DATASOURCE_USERNAME: kafeshka
      SPRING_DATASOURCE_PASSWORD: test123
    ports:
      - '8085:8080' # Expose Spring Boot app port as 8085 externally
    networks:
      kafeshanet:
        ipv4_address: 172.10.18.3 # Custom IPv4 address for Spring Boot app

networks:
  kafeshanet:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.10.18.0/24 # Define a custom subnet for the network
          gateway: 172.10.18.1
