version: '3.8'

services:
  kafeshka-mariadb:
    container_name: kafeshka-db
    image: mariadb:10.3.7
    environment:
      - MYSQL_USER=kafeshka
      - MYSQL_ROOT_PASSWORD=test123
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=kafeshka
    volumes:
      - "./volumes/mysql_init.sql:/docker-entrypoint-initdb.d/mysql_init.sql"
    networks:
      kafeshanet:
        ipv4_address: 172.10.18.2


  spring-app:
    image: redcopy/kafeshka-rs:latest
    container_name: kafeshka-rs
    restart: always
    depends_on:
      - kafeshka-mariadb
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.10.18.2:3306/kafeshka?useSSL=false&user=kafeshka&password=test123"
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_DATASOURCE_USERNAME=kafeshka
      - SPRING_DATASOURCE_PASSWORD=test123

      - SPRING_MYSQL_JDBC_URL=jdbc:mysql://172.10.18.2:3306/kafeshka?useSSL=false&user=kafeshka&password=test123"
      - SPRING_MYSQL_USER=kafeshka
      - SPRING_MYSQL_PASS=test123
      - HIBERNATE_DIALECT=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_GENERATE_DDL=true
      - KAFESH_SLEEP=10

    ports:
      - '8085:8080'
    networks:
      kafeshanet:
        ipv4_address: 172.10.18.3

networks:
  kafeshanet:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.10.18.0/24
          gateway: 172.10.18.1
