name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.run_id }}

    steps:
      - uses: actions/checkout@v3

      # Log in to Docker registry using API key and username
      - name: Log in to Docker registry
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # Build the Docker image
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag redcopy/kafeshka-rs:latest

      # Push the Docker image to Docker Hub
      - name: Push to Docker Hub
        run: docker push redcopy/kafeshka-rs:latest
        
      - name: Fetch project details
        id: project-details
        run: echo "::set-output name=project-name::-=KafeSHka RS=-"
        
      - name: Send Slack notification
        env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
            curl -X POST -H 'Content-type: application/json' --data '{
            "text": "✨🚀🔥  ImportanTE 🔥  !! \n Notification for Project:* ${{ steps.project-details.outputs.project-name }}\n*Build Status:* Docker Build redcopy/kafeshka-rs:latest Successful! 🎉"
            }' $SLACK_WEBHOOK_URL
