name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Log in to Docker registry using API key and username
      - name: Log in to Docker registry
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # Build the Docker image
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag redcopy/kafeshka-rs:latest

      # Push the Docker image to Docker Hub
      - name: Push to Docker Hub
        run: docker push redcopy/kafeshka-rs:latest
